### ISSUE TITLE
Impresion factura en PDF

### ISSUE THREAD

**Issue by SebastianCBA** [ivanalemunioz/afip-php#2]
Hola Ivan, excelente clase! Una consulta, conoces de alguna clase que genere el correspondiente archivo en PDF? Gracias!

**Comment by ivanalemunioz** [comment]
Sebastian, el PDF podes armarlo vos con alguna clase de PHP que sirva para esto, podrías usar [FPDF](http://www.fpdf.org/)

**Comment by SebastianCBA** [comment]
Si, ya instale y estoy usando DOMPDF, ahora estoy intentando encontrar alguna clase que genere el codigo de barras en  Interleaved 2 de 5, sabes de alguna?
Gracias!

**Comment by ivanalemunioz** [comment]
Esta es la que yo uso [PHP Barcode Generator](https://github.com/picqer/php-barcode-generator)
