### ISSUE TITLE
Consultar Datos Cliente

### ISSUE THREAD

**Issue by SebastianCBA** [ivanalemunioz/afip-php#3]
Hola! Es posible antes de facturar, hacer una consulta del cuit del cliente para saber si se le puede hacer factura A o no?
Gracias de antemano

**Comment by ivanalemunioz** [comment]
Seba, no hay ningún método en la facturación electronica para tal fin, no sabría decirte si existe en algún otro Web Service de la AFIP.
Lo que si sucede es que AFIP avisa cuando creas una factura y el CUIT no esta registrado en su servidores o esta inactivo

**Comment by SebastianCBA** [comment]
Muchas Gracias Ivan, la semana que viene pasare a produccion, cualquier cosa te aviso! Gracias de nuevo

**Comment by ivanalemunioz** [comment]
De nada, suerte

**Comment by ivanalemunioz** [comment]
Agregados los Web Services de consulta al padrón en 09051946b33309e098ab699a6c019f02f2fe4383
