### ISSUE TITLE
Error 10015

### ISSUE THREAD

**Issue by SebastianCBA** [ivanalemunioz/afip-php#4]
Hola Ivan, termine de probar los consumidores y cuando pase a factura A y B me saltaba el error "10015: El campo DocNro es inválido".

Lo solucione cambiando en en los wsfe1:

name="DocNro" type="s:long"
a
name="DocNro" type="s:string"

Lo dejo por si a alguno le sirve o para que le arregles.
Slds.
Gracias!

**Comment by ivanalemunioz** [comment]
Ese error te salia con el XML de producción o el de testing?

**Comment by SebastianCBA** [comment]
Hola, me salia en homo (testing)

Slds

**Comment by ivanalemunioz** [comment]
Yo no tuve ese problema, solo me aparecía si la pasaba un documento invalido, Ej. si seteaba tipo de documento CUIT y no le pasaba 11 caracteres, probaste parandole DocNro como numero? osea sin comillas
```php
$data = array( "DocNro" => 12345678123 )
```

**Comment by SebastianCBA** [comment]
Hola Ivan, si lo probe sin comillas, pero un cuit que empieza con 27 queda
afuera del maximo del longint 2147483647.
Entonces me decia que el nrodoc era invalido.

Slds

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-18 14:25 GMT-03:00 Ivan Muñoz <notifications@github.com>:

**Comment by SebastianCBA** [comment]
Hola Ivan, resulta que estaba consultando el cuit con https://soa.afip.gob.ar/sr-padron/v2/persona/CUIT pero parece ser que ya no funciona mas, sabes por donde puedo hacer la consulta?

**Comment by SebastianCBA** [comment]
Hola Ivan,, tengo que implementar esto 
http://www.afip.gob.ar/ws/ws_sr_padron_a10/manual_ws_sr_padron_a10_v1.1.pdf
utilizando renombrando tu libreria, actualizando los servidores y escribiendo los nuevos metodos crees que funcionará?

**Comment by ivanalemunioz** [comment]
Si Sebas se podría tomar como base la librería para implementar dicho Web Service

**Comment by SebastianCBA** [comment]
si, estoy intentando hacerlo pero me confundo con facilidad al no saber muchas cosas... resulta que va a ser una libreria que la va a consultar mucha gente en lugar de caer en las manos de pyafipws... ni bien la termine te la paso asi la subis al repo, o agregame a skype asi me das una manito ;)

**Comment by SebastianCBA** [comment]
actualmente se me esta trabando todo en esta parte de la funcion CreateServiceTA

		$results=$client->loginCms(array('in0'=>$CMS));
		if (is_soap_fault($results)) 
			throw new Exception("SOAP Fault: ".$results->faultcode."\n".$results->faultstring."\n", 4);

Me devuelve:

Notice: Undefined property: SoapFault::$faultcode in C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php on line 335

Fatal error: Uncaught Exception: SOAP Fault: in C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php:335 Stack trace: #0 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(272): App\Libraries\Afip->CreateServiceTA('ws_sr_padron_a1...') #1 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(200): App\Libraries\Afip->GetServiceTA('ws_sr_padron_a1...') #2 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(157): App\Libraries\Afip->GetWSInitialRequest('ws_sr_padron_a1...') #3 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(350): App\Libraries\Afip->ExecuteRequest('ws_sr_padron_a1...', 'getPersona', Array) #4 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(384): App\Libraries\Afip->GetPersona('26483649') #5 {main} thrown in C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php on line 335

algun tip?

**Comment by ivanalemunioz** [comment]
Si llego hasta esa Excepcion quiere decir que el error esta antes, podrías hacer un var_dump de $results para ver su contenido
````php
var_dump($results);
````

**Comment by SebastianCBA** [comment]
Si, tengo var_dumps por todos lados, ahora cambie para llamar al metodo dummy, pero se me traba en el mismo lugar, el var_dump de result me da esto:

object(SoapFault)#5 (8) { ["message":protected]=> string(0) "" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line":protected]=> int(334) ["trace":"Exception":private]=> array(6) { [0]=> array(6) { ["file"]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line"]=> int(334) ["function"]=> string(6) "__call" ["class"]=> string(10) "SoapClient" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(8) "loginCms" [1]=> array(1) { [0]=> array(1) { ["in0"]=> string(2460) " MIIHEwYJKoZIhvcNAQcCoIIHBDCCBwACAQExDzANBglghkgBZQMEAgEFADCCATsG CSqGSIb3DQEHAaCCASwEggEoPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0i VVRGLTgiPz4NCjxsb2dpblRpY2tldFJlcXVlc3QgdmVyc2lvbj0iMS4wIj48aGVh ZGVyPjx1bmlxdWVJZD4xNTExMzg0MzEyPC91bmlxdWVJZD48Z2VuZXJhdGlvblRp bWU+MjAxNy0xMS0yMlQxMjo0ODozMi0wODowMDwvZ2VuZXJhdGlvblRpbWU+PGV4 cGlyYXRpb25UaW1lPjIwMTctMTEtMjJUMTM6MDg6MzItMDg6MDA8L2V4cGlyYXRp b25UaW1lPjwvaGVhZGVyPjxzZXJ2aWNlPndzX3NyX3BhZHJvbl9hMTA8L3NlcnZp Y2U+PC9sb2dpblRpY2tldFJlcXVlc3Q+DQqgggNPMIIDSzCCAjOgAwIBAgIIexFR ATE3WOwwDQYJKoZIhvcNAQENBQAwODEaMBgGA1UEAwwRQ29tcHV0YWRvcmVzIFRl c3QxDTALBgNVBAoMBEFGSVAxCzAJBgNVBAYTAkFSMB4XDTE3MTAxNzIxNDkwNFoX DTE5MTAxNzIxNDkwNFowMTEUMBIGA1UEAwwLRWxlY3Ryb25pY2ExGTAXBgNVBAUT EENVSVQgMjAyMzU3MjM5MDYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB AQDVDGFVcN2XXJKt9G06QDoIROiHXmPHUZE9cM/HWQ6bpKsexVlTOsJoPZUb9Azg neejQg5yNN0eOlv182v9oqxNN58m1OPNR8USOdAvMs1jbXcwPZiUsuzJucEMdjMw 1xQqnNfllYEOh8tc9D1Ddtq2ebtE4hhJtbmHEZalqIdEOKqBbOG9+YW5Rwv2Ch7S +KrTKnx8qk5iLjuoVGSmu3riZo0XIVNdAG3PWbEuex6C9Z5AbTUc1mjQ9nUfMV/a A9OaTJkTDSt2bSyJjiQSuNvCDxnfDVS42nOu+bbZv4nN9+NDF8yhaO1Ywa96OazO gw+Dde1vZKk3ldl9DJV2uXknAgMBAAGjYDBeMAwGA1UdEwEB/wQCMAAwHwYDVR0j BBgwFoAUs7LT//3put7eja8RIZzWIH3yT28wHQYDVR0OBBYEFLjtp2Ta4lJrWgRW CJRe3gLr9v3NMA4GA1UdDwEB/wQEAwIF4DANBgkqhkiG9w0BAQ0FAAOCAQEAJD/f XHrie2KI8GHhL5L6opqoBjWnPu4FO9yBI3fBAlVaD1oCppK8QTMCWCf5YLWY/tei LVpbEnCg17CLzkzWummr308hNU/veKorC18Xc3qAaypp05JmHhJD98KojNObfDyL 1O/qBIniq6AlmEo2qg+ssBcz5jn93BW+vfEe20Ya2/pzWV3LIsgapp4JJO8iacrN zJsJGlT0cZ8A2qSmiS8FEdWauhwjVyT5TJlPwzZScvwbThpIPawF4qsASw+rY8EW ydxvVOabzUS87NW2DsJ5uyzCvRpOmgvG6aASUjlwfW48Tu0gbgWNkXjIlC3AbIK+ rU8dd6QxG0+TrgBeHjGCAlYwggJSAgEBMEQwODEaMBgGA1UEAwwRQ29tcHV0YWRv cmVzIFRlc3QxDTALBgNVBAoMBEFGSVAxCzAJBgNVBAYTAkFSAgh7EVEBMTdY7DAN BglghkgBZQMEAgEFAKCB5DAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqG SIb3DQEJBTEPFw0xNzExMjIyMDU4MzJaMC8GCSqGSIb3DQEJBDEiBCAcS/G1cl+R DoZ4E+JhHa4u/0OpJ+ua2vwrzYyHITn68jB5BgkqhkiG9w0BCQ8xbDBqMAsGCWCG SAFlAwQBKjALBglghkgBZQMEARYwCwYJYIZIAWUDBAECMAoGCCqGSIb3DQMHMA4G CCqGSIb3DQMCAgIAgDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0D AgIBKDANBgkqhkiG9w0BAQEFAASCAQCGXn+YEjiwx2ICE2lTn1E40cdbTksxEBpP 1O5oDJQhriTq3gyRWdCraN8HRjoq7L8YhKR32wTbdni9Ixq7f5kWQjTB/JNd9xkQ MAVQt4tNkI+Y7tOoqIqy3ccpxxC0jIFC/QDlBZJjUtDeCqhnNa5xqhKBjcYFuHcP PPAtkoDi+M8R3xG9NvZnbxTgcoVSh5fNeW4P5ttYCAzvVLIHi4QOBdU6POrCvlrx CY7gc9YHHpBA/gBOW3bOG8U+fmHHTFeARpo9lrsiN989Q6LrouSjF7PhlgfIDbEo brQ2wUlu5zBRLncuqAoF0/vSs8e+5ZxBiKmqlsYgTc0N5gxIQncg " } } } } [1]=> array(6) { ["file"]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line"]=> int(274) ["function"]=> string(15) "CreateServiceTA" ["class"]=> string(18) "App\Libraries\Afip" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(16) "ws_sr_padron_a10" } } [2]=> array(6) { ["file"]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line"]=> int(200) ["function"]=> string(12) "GetServiceTA" ["class"]=> string(18) "App\Libraries\Afip" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(16) "ws_sr_padron_a10" } } [3]=> array(6) { ["file"]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line"]=> int(155) ["function"]=> string(19) "GetWSInitialRequest" ["class"]=> string(18) "App\Libraries\Afip" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(16) "ws_sr_padron_a10" } } [4]=> array(6) { ["file"]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line"]=> int(352) ["function"]=> string(14) "ExecuteRequest" ["class"]=> string(18) "App\Libraries\Afip" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(16) "ws_sr_padron_a10" [1]=> string(5) "dummy" } } [5]=> array(6) { ["file"]=> string(85) "C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php" ["line"]=> int(387) ["function"]=> string(10) "GetPersona" ["class"]=> string(18) "App\Libraries\Afip" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(8) "26483649" } } } ["previous":"Exception":private]=> NULL ["faultstring"]=> string(0) "" }

**Comment by SebastianCBA** [comment]
Si acceso desde el navegador al servidor de conexion me devuelve este resultado, esta bien que retorne eso?

![image](https://user-images.githubusercontent.com/22308520/33150112-eaf64934-cfb0-11e7-9514-88321a6e3b56.png)

**Comment by SebastianCBA** [comment]
aparentemente segun este thread: 
https://groups.google.com/forum/#!topic/pyafipws/TzHH9Z1f0RA
tengo que usar el de alcance4
voy a hacer la relacion a la afip y te digo algo, porque me parece que el 10 no esta funcionando

**Comment by SebastianCBA** [comment]
nada, obtengo casi el mismo error:

<br />
--
  | <b>Notice</b>:  Undefined property: SoapFault::$faultcode in <b>C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php</b> on line <b>337</b><br />
  | <br />
  | <b>Fatal error</b>:  Uncaught Exception: SOAP Fault:
  |  
  | in C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php:337
  | Stack trace:
  | #0 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(274): App\Libraries\Afip-&gt;CreateServiceTA('ws_sr_padron_a4')
  | #1 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(200): App\Libraries\Afip-&gt;GetServiceTA('ws_sr_padron_a4')
  | #2 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(155): App\Libraries\Afip-&gt;GetWSInitialRequest('ws_sr_padron_a4')
  | #3 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(352): App\Libraries\Afip-&gt;ExecuteRequest('ws_sr_padron_a4', 'dummy')
  | #4 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php(387): App\Libraries\Afip-&gt;GetPersona('26483649')
  | #5 {main}
  | thrown in <b>C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\grupofase.com.ar\public\Afip-persona.php</b> on line <b>337</b><br />

**Comment by SebastianCBA** [comment]
Una pregunta, tengo que generar un nuevo TRA con esta estructura:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:a4="http://a4.soap.ws.server.puc.sr/">
 <soapenv:Header/>
 <soapenv:Body>
 <a4:dummy/>
 </soapenv:Body>
</soapenv:Envelope>


Correcto?

**Comment by ivanalemunioz** [comment]
El token de autenticacion te lo debería generar el metodo **GetServiceTA** sin tener que hacerle cambios al codigo, solo enviandole como parametro el id der servicio, en este caso "ws_sr_padron_a10"
````php
$token = $Afip->GetServiceTA("ws_sr_padron_a10");
````

Te devolvería un Objeto del tipo `WSAA_TA` que contiene las propiedades token y sign, probaste usarlo asi?

**Comment by SebastianCBA** [comment]
Mira, los cambios que hice sobre la base son los siguientes:
En el constructor: 
```
			$this->WSFE_WSDL 	= $this->RES_FOLDER.'wsfe1.wsdl';
			$this->WSAA_URL 	= 'https://wsaahomo.afip.gov.ar/ws/services/LoginCms';
			$this->WSFE_URL 	= 'https://wswhomo.afip.gov.ar/wsfev1/service.asmx';
```

por

			```
$this->WSFE_WSDL 	= $this->RES_FOLDER.'wsfe1.wsdl';
			$this->WSAA_URL 	= 'https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA4';
			$this->WSFE_URL 	= 'https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA4?wsdl';
```

En la funcion  CreateServiceTA($service), que en service llega el valor 'ws_sr_padron_a4', cambie esto:

		```
$TRA = new SimpleXMLElement(
		'<?xml version="1.0" encoding="UTF-8"?>' .
		'<loginTicketRequest version="1.0">'.
		'</loginTicketRequest>');
		$TRA->addChild('header');
		$TRA->header->addChild('uniqueId',date('U'));
		$TRA->header->addChild('generationTime',date('c',date('U')-600));
		$TRA->header->addChild('expirationTime',date('c',date('U')+600));
		$TRA->addChild('service',$service);
		$TRA->asXML($this->RES_FOLDER.'TRA-'.$service.'.xml');
```
por esto:
		```
$TRA = new SimpleXMLElement(
		'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
			xmlns:a4="http://a4.soap.ws.server.puc.sr/">
			 <soapenv:Header/>
			 <soapenv:Body>
			 <a4:dummy/>
			 </soapenv:Body>
			</soapenv:Envelope>');
		$TRA->asXML($this->RES_FOLDER.'TRA-'.$service.'.xml');
```

Luego agrege la funcion
```
	public function GetDummy()
	{
		$return = $this->ExecuteRequest('ws_sr_padron_a4', 'dummy');
		var_dump($return); exit();

	}	
```
y al final ejecuto

```
        $afip = new Afip(array('CUIT' => $cuit));
        $persona = $afip->GetDummy;
        //var_dump($persona);
```

**Comment by ivanalemunioz** [comment]
Pero estas implementando el padron alcance 10 o 4?
Me pasaste este link
http://www.afip.gob.ar/ws/ws_sr_padron_a10/manual_ws_sr_padron_a10_v1.1.pdf
y al pareces estas implementando este 
http://www.afip.gob.ar/ws/ws_sr_padron_a4/manual_ws_sr_padron_a4_v1.1.pdf
 
Ademas por lo que veo en el constructor ninguna de las variables que cambiaste tiene el contenido correcto , y como te dije la funcion CreateServiceTA no deberias modificarla

Decime que Web Service estas implementando así te puedo brindar una mayor ayuda

**Comment by SebastianCBA** [comment]
Mira, el 10 parece estar caido, y como dicen por ahi hay que usar el 4... Los resultados del 10 paracen ser mas completos, pero ante la inestabilidad del mismo, vamos a usar el 4...
Me falta el archivo TA-ws_sr_padron_a4.xml y al querer generarlo es donde da error.

**Comment by ivanalemunioz** [comment]
El archivo TA-ws_sr_padron_a4.xml se genera automaticamente con CreateServiceTA, pero no es necesario que lo modifiques ni le hagas cambios.

Proba sin hacer cambios en el codigo original si podes obtener el token con 
```php
$token = $Afip->GetServiceTA("ws_sr_padron_a4");
```

hace un var_dump para ver que obtenés

**Comment by SebastianCBA** [comment]
Ahi reestableci tu codigo y de la funcion:

```
	public function GetDummy()
	{

        $token = $this->GetServiceTA("ws_sr_padron_a4");
        var_dump($token);

		$return = $this->ExecuteRequest('ws_sr_padron_a4', 'dummy');
		var_dump($return); exit();
	}
```	
Se desprende:


```
object(WSAA_TA)#7 (2) {
--
  | ["token"]=>
  | object(SimpleXMLElement)#8 (1) {
  | [0]=>
  | string(744) "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/Pgo8c3NvIHZlcnNpb249IjIuMCI+CiAgICA8aWQgc3JjPSJDTj13c2FhaG9tbywgTz1BRklQLCBDPUFSLCBTRVJJQUxOVU1CRVI9Q1VJVCAzMzY5MzQ1MDIzOSIgdW5pcXVlX2lkPSIzMDM1MjU5ODM5IiBnZW5fdGltZT0iMTUxMTM5NDUxNCIgZXhwX3RpbWU9IjE1MTE0Mzc3NzQiLz4KICAgIDxvcGVyYXRpb24gdHlwZT0ibG9naW4iIHZhbHVlPSJncmFudGVkIj4KICAgICAgICA8bG9naW4gZW50aXR5PSIzMzY5MzQ1MDIzOSIgc2VydmljZT0id3Nfc3JfcGFkcm9uX2E0IiB1aWQ9IlNFUklBTE5VTUJFUj1DVUlUIDIwMjM1NzIzOTA2LCBDTj1lbGVjdHJvbmljYSIgYXV0aG1ldGhvZD0iY21zIiByZWdtZXRob2Q9IjIyIj4KICAgICAgICAgICAgPHJlbGF0aW9ucz4KICAgICAgICAgICAgICAgIDxyZWxhdGlvbiBrZXk9IjIwMjM1NzIzOTA2IiByZWx0eXBlPSI0Ii8+CiAgICAgICAgICAgIDwvcmVsYXRpb25zPgogICAgICAgIDwvbG9naW4+CiAgICA8L29wZXJhdGlvbj4KPC9zc28+Cg=="
  | }
  | ["sign"]=>
  | object(SimpleXMLElement)#9 (1) {
  | [0]=>
  | string(172) "BVi4CtEqs9wD8oNyR4kYECC55XdLEG/K5cYB9y4/W7ahBFuyPwHS1kOn7APwK4fCQQbIYdzXS1R8VVFK5ablJI+7PL+gfZrQRbcyvLG8L51UVI2WFCu+5SRVk9xsSVGo9r3eAFu4vERB1+X2Bz4qGAYuttfNWVvAd+9BrSNhDVs="
  | }
  | }
  | <br />
  | <b>Fatal error</b>:  Uncaught Exception: SOAP Fault: Sender
  | Function (&quot;dummy&quot;) is not a valid method for this service
  | in C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\ws_sr_padron_a4\Afip-persona.php:159
  | Stack trace:
  | #0 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\ws_sr_padron_a4\Afip-persona.php(361): Afip-&gt;ExecuteRequest('ws_sr_padron_a4', 'dummy')
  | #1 C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\ws_sr_padron_a4\Afip-persona.php(396): Afip-&gt;GetDummy()
  | #2 {main}
  | thrown in <b>C:\Bitnami\wampstack-7.1.10-1\apache2\htdocs\ws_sr_padron_a4\Afip-persona.php</b> on line <b>159</b><br />

```

**Comment by ivanalemunioz** [comment]
Bueno supongo que borraste  el código que esta al principio de ExecuteRequest, me refiero a 

```php
if ($service != 'wsfe') {
	throw new Exception('Service not implemented yet');
}
```

Estoy en lo correcto?

P/D: Ya nos fuimos mucho del tema acá respondeme al correo que encontrás en https://github.com/ivanalemunioz/afip-php#soporte-y-contacto
